export function priceValue(dish) {
  return parseFloat(dish.price.replace(/[^0-9.]/g, ''));
}

export const categories = [
  { id: 'all', label: 'All Dishes' },
  { id: 'grill', label: 'From the Grill' },
  { id: 'raw-bar', label: 'Raw Bar' },
  { id: 'sides', label: 'Sides' },
  { id: 'drinks', label: 'Drinks' },
  { id: 'dessert', label: 'Dessert' },
];

export const dishes = [
  {
    id: 1,
    name: 'Whole Fired Sea Bream',
    price: '£28',
    desc: 'Line-caught, salt-crusted, grilled whole over oak with lemon and wild fennel.',
    tag: 'Gluten-free',
    category: 'grill',
    rating: 4.8,
    reviews: 312,
    img: 'https://images.unsplash.com/photo-1432139509613-5c4255815697?auto=format&fit=crop&w=700&q=75',
  },
  {
    id: 2,
    name: '45-Day Dry-Aged Rib',
    price: '£36',
    desc: 'Hill-farm beef, bark-charred over embers, bone marrow butter.',
    tag: 'Serves two',
    category: 'grill',
    rating: 4.9,
    reviews: 204,
    img: 'https://images.unsplash.com/photo-1600891964092-4316c288032e?auto=format&fit=crop&w=700&q=75',
  },
  {
    id: 3,
    name: 'Charred Octopus',
    price: '£19',
    desc: 'Slow-braised then finished on the grill, smoked paprika, potato ash.',
    tag: 'Gluten-free',
    category: 'raw-bar',
    rating: 4.6,
    reviews: 141,
    img: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?auto=format&fit=crop&w=700&q=75',
  },
  {
    id: 4,
    name: 'Embered Root Vegetables',
    price: '£14',
    desc: 'Whatever came from the hill farm this week, cooked directly in the coals.',
    tag: 'Vegan',
    category: 'sides',
    rating: 4.5,
    reviews: 97,
    img: 'https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?auto=format&fit=crop&w=700&q=75',
  },
  {
    id: 5,
    name: 'Harbor Oysters, Half Dozen',
    price: '£16',
    desc: "Today's catch, shucked to order, mignonette and hot sauce.",
    tag: 'Raw bar',
    category: 'raw-bar',
    rating: 4.9,
    reviews: 256,
    img: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=700&q=75',
  },
  {
    id: 6,
    name: 'Fire-Caramelized Custard',
    price: '£9',
    desc: 'Torched to order at the table, bay leaf cream, burnt honey.',
    tag: 'Vegetarian',
    category: 'dessert',
    rating: 4.8,
    reviews: 183,
    img: 'https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&w=700&q=75',
  },
  {
    id: 7,
    name: 'Wood-Fired King Prawns',
    price: '£22',
    desc: 'Whole prawns, shell on, grilled hot and fast with garlic butter and lemon.',
    tag: 'Gluten-free',
    category: 'raw-bar',
    rating: 4.7,
    reviews: 128,
    img: 'https://images.unsplash.com/photo-1559737558-2f5a35f4523b?auto=format&fit=crop&w=700&q=75',
  },
  {
    id: 8,
    name: "Chef's Ice-Cold Seafood Tower",
    price: '£48',
    desc: 'The morning catch laid out on ice: fin fish, shellfish and whatever else came in.',
    tag: 'Serves two',
    category: 'raw-bar',
    rating: 4.9,
    reviews: 76,
    img: 'https://images.unsplash.com/photo-1615141982883-c7ad0e69fd62?auto=format&fit=crop&w=700&q=75',
  },
  {
    id: 9,
    name: 'Crispy-Skin Salmon, Herb Risotto',
    price: '£26',
    desc: 'Fired skin-on until it cracks, rested over a bright herb risotto.',
    tag: 'Gluten-free',
    category: 'grill',
    rating: 4.8,
    reviews: 165,
    img: 'https://images.unsplash.com/photo-1580476262798-bddd9f4b7369?auto=format&fit=crop&w=700&q=75',
  },
  {
    id: 10,
    name: 'Peppercorn-Crusted Smoked Brisket',
    price: '£32',
    desc: 'Dry-rubbed, smoked low over oak for hours, sliced to order.',
    tag: 'Serves two',
    category: 'grill',
    rating: 4.9,
    reviews: 142,
    img: 'https://images.unsplash.com/photo-1592894869086-f828b161e90a?auto=format&fit=crop&w=700&q=75',
  },
  {
    id: 11,
    name: 'Fire-Charred Wings, Blue Cheese Dip',
    price: '£13',
    desc: 'Charred over the coals and glazed, served with a cold blue cheese dip.',
    tag: 'Gluten-free',
    category: 'grill',
    rating: 4.6,
    reviews: 201,
    img: 'https://images.unsplash.com/photo-1608039755401-742074f0548d?auto=format&fit=crop&w=700&q=75',
  },
  {
    id: 12,
    name: 'Charred Tomato Bruschetta',
    price: '£11',
    desc: 'Toasted sourdough, fire-blistered tomato and pepper, good olive oil.',
    tag: 'Vegan',
    category: 'sides',
    rating: 4.5,
    reviews: 88,
    img: 'https://images.unsplash.com/photo-1625938144755-652e08e359b7?auto=format&fit=crop&w=700&q=75',
  },
  {
    id: 13,
    name: 'Smoked Old Fashioned',
    price: '£12',
    desc: 'Bourbon, oak smoke, orange peel. Poured tableside.',
    tag: 'Drinks',
    category: 'drinks',
    rating: 4.8,
    reviews: 94,
    img: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?auto=format&fit=crop&w=700&q=75',
  },
  {
    id: 14,
    name: 'Garden Mint & Lime Spritz',
    price: '£9',
    desc: 'Fresh lime, mint and soda over ice. Non-alcoholic on request.',
    tag: 'Vegan',
    category: 'drinks',
    rating: 4.6,
    reviews: 71,
    img: 'https://images.unsplash.com/photo-1546171753-97d7676e4602?auto=format&fit=crop&w=700&q=75',
  },
  {
    id: 15,
    name: 'Classic Cheesecake, Mixed Berries',
    price: '£10',
    desc: 'Baked in-house, finished with raspberry and blueberry.',
    tag: 'Vegetarian',
    category: 'dessert',
    rating: 4.7,
    reviews: 109,
    img: 'https://images.unsplash.com/photo-1524351199678-941a58a3df50?auto=format&fit=crop&w=700&q=75',
  },
];

export const heroImages = [
  { id: 1, src: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1800&q=75', alt: 'Wood-fire grill with flames at Ember & Salt' },
  { id: 2, src: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1800&q=75', alt: 'Flames on the open grill' },
  { id: 3, src: 'https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?auto=format&fit=crop&w=1800&q=75', alt: 'Chef tending the open fire grill' },
  { id: 4, src: 'https://images.unsplash.com/photo-1600891964092-4316c288032e?auto=format&fit=crop&w=1800&q=75', alt: '45-day dry-aged rib, bark-charred over embers' },
  { id: 5, src: 'https://images.unsplash.com/photo-1432139509613-5c4255815697?auto=format&fit=crop&w=1800&q=75', alt: 'Whole grilled sea bream' },
  { id: 6, src: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1800&q=75', alt: 'Restaurant dining room interior' },
  { id: 7, src: 'https://images.unsplash.com/photo-1560717845-968823efbee1?auto=format&fit=crop&w=1800&q=75', alt: 'Seared salmon plated close up' },
  { id: 8, src: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=1800&q=75', alt: 'Skewers and vegetables over the fire' },
  { id: 9, src: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1800&q=75', alt: 'The dining room in the evening' },
  { id: 10, src: 'https://images.unsplash.com/photo-1590846406792-0adc7f938f1d?auto=format&fit=crop&w=1800&q=75', alt: 'Evening ambiance in the dining room' },
];

export const galleryImages = [
  { id: 1, src: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1200&q=75', alt: 'Flames on the open grill' },
  { id: 2, src: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=75', alt: 'Restaurant dining room interior' },
  { id: 3, src: 'https://images.unsplash.com/photo-1560717845-968823efbee1?auto=format&fit=crop&w=1200&q=75', alt: 'Seared salmon plated close up' },
  { id: 4, src: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=1200&q=75', alt: 'Bar and wine shelves' },
  { id: 5, src: 'https://images.unsplash.com/photo-1424847651672-bf20a4b0982b?auto=format&fit=crop&w=1200&q=75', alt: 'Chef plating food in the kitchen' },
  { id: 6, src: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=1200&q=75', alt: 'Skewers and vegetables over the fire' },
  { id: 7, src: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=75', alt: 'Grilled dishes plated and ready to serve' },
  { id: 8, src: 'https://images.unsplash.com/photo-1544148103-0773bf10d330?auto=format&fit=crop&w=1200&q=75', alt: 'Cocktail on the bar' },
  { id: 9, src: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1200&q=75', alt: 'The dining room in the evening' },
  { id: 10, src: 'https://images.unsplash.com/photo-1590846406792-0adc7f938f1d?auto=format&fit=crop&w=1200&q=75', alt: 'Evening ambiance in the dining room' },
];

export const features = [
  {
    id: 1,
    title: 'No gas, ever',
    desc: 'Every plate that leaves the kitchen has touched the same oak fire. Nothing here comes off a burner.',
  },
  {
    id: 2,
    title: 'Landed that morning',
    desc: "We buy whole from three day-boats on the harbor. If it wasn't caught today, it isn't on the menu.",
  },
  {
    id: 3,
    title: 'No corkage, Sundays',
    desc: "Bring a bottle from your own cellar on Sundays and we'll pour it free. Ask your server for glasses.",
  },
];

export const testimonials = [
  {
    id: 1,
    name: 'Elon Musk',
    role: 'SpaceX, Tesla, Twitter',
    rating: 5,
    text: 'Asked for admin privileges on the dessert menu and they just brought me two. 10/10 would deploy again.',
  },
  {
    id: 2,
    name: 'Alexandra Wong',
    role: 'AI engineer, full stack',
    rating: 5,
    text: 'Brought the whole engineering team here after a rough sprint. Nobody crashed, everyone shipped happy.',
  },
  {
    id: 3,
    name: 'Mark zuckerberg',
    role: 'META CEO',
    rating: 4,
    text: 'Food came out faster than our staging deploys. Docked one star only because the wifi password is not on the menu.',
  },
  {
    id: 4,
    name: 'Jeff Bezos',
    role: '200ms to the table',
    rating: 5,
    text: 'Low latency, high flavor. The brisket alone is worth the round trip.',
  },
  {
    id: 5,
    name: 'Dario Amodei',
    role: 'CEO, Anthropic',
    rating: 5,
    text: 'The brisket was a revelation. The octopus was a revelation. The whole experience was a revelation. I am enlightened.',
  },
  {
    id: 6,
    name: 'Larry Page',
    role: 'Google search for "best brisket in Bristol"',
    rating: 5,
    text: 'Got root on the tasting menu and never looked back. Bring your CTO, they will approve the budget.',
  },
  {
    id: 7,
    name: 'Jensen Huang ',
    role: 'CEO, NVIDIA',
    rating: 4,
    text: 'Came here with the whole graphics team. The brisket was a solid release, but the octopus was a game-changer,tasted like ramen.',
  },
  {
    id: 8,
    name: 'Daniel Paul',
    role: 'Full-stack, fully fed',
    rating: 5,
    text: 'The food here is consistently excellent. The service is top-notch.',
  },
];

export const restaurantInfo = {
  name: 'Ember & Salt',
  address: 'Harbor Quay 12, Bristol Docks BS1 4RN',
  hours: 'Tue–Sun, 18:00–23:00 · Closed Mondays',
  phone: '+44 117 555 0118',
  email: 'table@emberandsalt.co',
};
